# Generated by Django 4.0.2 on 2025-08-01 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_orders_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
